# Generated by Django 5.2.8 on 2025-11-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='album-photo/')),
            ],
        ),
        migrations.CreateModel(
            name='MusicSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('artist', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='MusicSet-photo/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('audio_file', models.FileField(help_text='Загрузить аудио файл', upload_to='songs/Y%/m%/d%/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.album', verbose_name='albums')),
            ],
        ),
    ]
